# Generated by Django 4.2.21 on 2025-06-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='book_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
