# Generated by Django 4.2.21 on 2025-06-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrowrecord_book_title_borrowrecord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
