# Generated by Django 4.2.21 on 2025-06-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_borrowrecord_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
