# Generated by Django 4.2.21 on 2025-06-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_borrowrecord_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='punish',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('returned', 'Đã trả'), ('overdue', 'Quá hạn'), ('failed', 'Từ chối')], default='pending', max_length=20),
        ),
    ]
