# Generated by Django 4.2.21 on 2025-06-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='mark_point',
        ),
    ]
