# Generated by Django 4.2.21 on 2025-06-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_mark_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mark_point',
            field=models.CharField(default='0.0', max_length=255),
        ),
    ]
