# Generated by Django 4.2.21 on 2025-06-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_mark_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='mark_point',
        ),
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
